development:
  APP_SECRET: "503b41746c64c50a909f16fc4804bf8e"
  VERIFY_TOKEN: "changeinit"
  CLIENT_TOKEN: "f104d40af64abf87c561dbf781440c14"
  ACCESS_TOKEN: "EAAfWRaKam6cBAG6M4ktMhJBkouNGo5WwmuveBkFC7jkneFFw6ZAtAQawWkJZCWjkozelL5fAeZAknu7NASJ4fOSW6z5Hkyx3L5uy0y59vpxIJZCfyTHI1EjPIGFKSYDOz6ZA45mnQz8urN5RAfAhDZC5pemzwSrqGk7q4kZCVtwcQZDZD"
# production:
#   APP_SECRET: "a4079e9ed1cd0ecd4cc291e19ab52560"
#   VERIFY_TOKEN: "changeinit"
#   CLIENT_TOKEN: "baa1514e295aeb915aa356b00263a805"
#   ACCESS_TOKEN: "EAAZA8lrvJEDABAMHDgXuVHdcZB67l2JZAhgU1Wyh4rVZCZBEX7sOCiMZBdjYL0vF5f1WkpdurZBqAFpwMZAnNTQo91dv7zPeu7BejMbIJoVblL8kkZAowFETKR0j9EPQqdT24IAZAIZAsNYRB87iHWnx5EdMZAkdN2gSrQJHOiSFWDvM8QZDZD"
#   APP_ID: "1825836697718832"
#   FB_SECRET: "cd17a512c44b034af656e0f5709fc571"
#   FB_ID: "221166698521472"


