development:
  APP_SECRET: "a4079e9ed1cd0ecd4cc291e19ab52560"
  VERIFY_TOKEN: "changeinit"
  CLIENT_TOKEN: "baa1514e295aeb915aa356b00263a805"
  ACCESS_TOKEN: "EAAZA8lrvJEDABAMHDgXuVHdcZB67l2JZAhgU1Wyh4rVZCZBEX7sOCiMZBdjYL0vF5f1WkpdurZBqAFpwMZAnNTQo91dv7zPeu7BejMbIJoVblL8kkZAowFETKR0j9EPQqdT24IAZAIZAsNYRB87iHWnx5EdMZAkdN2gSrQJHOiSFWDvM8QZDZD"
