# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK

development:
  APP_SECRET: "a4079e9ed1cd0ecd4cc291e19ab52560"
  VERIFY_TOKEN: "changeinit"
  CLIENT_TOKEN: "baa1514e295aeb915aa356b00263a805"
  ACCESS_TOKEN: "EAAZA8lrvJEDABAMHDgXuVHdcZB67l2JZAhgU1Wyh4rVZCZBEX7sOCiMZBdjYL0vF5f1WkpdurZBqAFpwMZAnNTQo91dv7zPeu7BejMbIJoVblL8kkZAowFETKR0j9EPQqdT24IAZAIZAsNYRB87iHWnx5EdMZAkdN2gSrQJHOiSFWDvM8QZDZD"
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
